---
name: "build"

on:
  push:
    branches:
      - "mainline"
  pull_request:
    branches:
      - "mainline"

jobs:
  test:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: [2.7, 3.7, 3.8]
    steps:
      - uses: "actions/checkout@v2"
        with:
          fetch-depth: 1
      - name: "Set up Python ${{ matrix.python-version }}"
        uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "run tests"
        run: "make test"
  maybe_bump:
    if: github.ref == 'refs/heads/mainline'
    runs-on: "ubuntu-latest"
    needs: "test"
    steps:
      - uses: "actions/checkout@v2"
        with:
          fetch-depth: 1
      - name: "Set up Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"
      - name: "dat env tho"
        run: "make testenv"
      - name: "Maybe bump version"
        run: |
            git config user.email "sysop@eghetto.ca"
            git config user.name "An Automaton"
            git remote set-url origin "$(git config --get remote.origin.url | sed 's#http.*com/#git@github.com:#g')"
            eval `ssh-agent -t 300 -s`
            ssh-add - <<< "${{secrets.DEPLOY_KEY}}"
            mkdir -p ~/.ssh/
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config --get remote.origin.url
            git branch -la
            ssh-add -l
            ./avakas bump . auto --branch=mainline
            ssh-agent -k
  publish:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: "ubuntu-latest"
    needs: "test"
    steps:
      - uses: "actions/checkout@v2"
        with:
          fetch-depth: 1
      - name: "Set up Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"
      - name: "Build a package"
        run: "make package"
      - name: "Publish to pypi"
        uses: "pypa/gh-action-pypi-publish@v1.3.1"
        with:
          user: "__token__"
          password: "${{ secrets.PYPI_TOKEN }}"
